POST http://127.0.0.1:8000/stbookinventory/login
Content-Type: application/json
{"email": "marvinalamu_1@live.com", "password":"1234"}

###

POST http://127.0.0.1:8000/stbookinventory/signup
Content-Type: application/json
{"email": "marvinalamu_1@live.com", "password":"1234"}

###

GET http://127.0.0.1:8000/stbookinventory/test_token
Content-Type: application/json
Authorization: Token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

{}