# Generated by Django 4.2.6 on 2023-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STBookInventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('General User', 'General User'), ('Staff Member', 'Staff Member'), ('Admin', 'Admin')], default='General User', max_length=100, verbose_name='Account Type'),
        ),
    ]
